name: PermissionBalance
main: com.coollord22.permissionbalance.PermissionBalance
version: ${project.version}
author: CoolLord22
api-version: 1.13
depend: [Essentials]
commands:
  permissionbalance:
    description: Administrate the PermissionBalance plugin
    aliases: [pb]
    usage: |
        §aPermissionBalance §7(Permission based balance manager) 
        §7Version: ${project.version}
        §a/pb reload §7- reload config
    permission: permissionbalance.admin

permissions:
  permissionbalance.admin.reload:
    description: Allows you to reload the config
    default: op